### ISSUE TITLE
Running Susi

### ISSUE THREAD

**Issue by ezamorab** [secure-software-engineering/SuSi#16]
Hi, I have some problems... could you help me, please?

When I try to run Susi with the cmd command, it starts but then I get a problem:

```
...
...
Class com.android.phone.BluetoothHandsfree$13 not found
Class com.android.providers.userdictionary.DictionaryBackupAgent not found
Class com.android.mms.ui.AttachmentEditor not found
1630 methods purged down to 508
Created automatic annotations starting from 0 methods
Loaded 40132 methods from Android JAR
Created automatic annotations starting from 38 methods
Annotated sources: 63, sinks: 198, neither: 285
Exception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;
	at de.ecspride.sourcesinkfinder.features.ParameterInCallFeature.appliesInternal(ParameterInCallFeature.java:118)
	at de.ecspride.sourcesinkfinder.features.AbstractSootFeature.applies(AbstractSootFeature.java:110)
	at de.ecspride.sourcesinkfinder.SourceSinkFinder.analyzeSourceSinkWeka(SourceSinkFinder.java:460)
	at de.ecspride.sourcesinkfinder.SourceSinkFinder.run(SourceSinkFinder.java:126)
	at de.ecspride.sourcesinkfinder.SourceSinkFinder.main(SourceSinkFinder.java:95)

```

Do you know why?

I also want to know if Susi runs with the newest versions of android.

Thanks in advance!

**Comment by ashiq35** [comment]
Hi, 
Do you know from where I get the soot-trunk.jar and susi.jar file ?

Thanks in advance.

**Comment by StevenArzt** [comment]
You can get the Soot JAR file from the Soot project on Github: https://github.com/Sable/soot. The susi.jar file is simply the compiled version of the Susi project.

**Comment by ashiq35** [comment]
@StevenArzt  Thank you I already did it and it's working :D 

Just a silly question, is the SuSi can analyze the latest android version. And could you please tell us how could we make the android.jar from the latest android version. 

I read few peoples are willingly waiting to know is SuSi's compatibility with the latest android version.

Thanks :)

**Comment by StevenArzt** [comment]
I haven't tried SuSi with newer Android versions, so I can't tell for sure. However, I would assume that it should just work fine. For generating the full Android framework JAR, there are tutorials online to extract the dex/odex files from a phone or emulator and decompile them into JARs. You can also build the Android open source project to get the bytecode, which should be the most straight-forward solution.

**Comment by ezamorab** [comment]
Hi, @StevenArzt 

Could you help me with my problem, please?

Thanks a lot!

**Comment by StevenArzt** [comment]
@ezamorab You seem to be using an outdated or broken version of Soot. Please try again with the newest version of Soot and re-compile Susi against that version just to be sure that everything matches.

**Comment by dzih526** [comment]
soot 3.2.0 works well. but soot 4.0.0 doesn't work for me
